# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: flake8
        args: [--count,--ignore,E501,--statistics,--exclude,.git,__pycache__]
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [ -d W0511 , -d C0114 , -d C0116 , -d C0115 , -d C0301 , -d C0103 , -d R0913 , -d R0914 , -d R0902 , -d R0912 , -d R0801 , -d W0212 , -d W0223 , -d E1101 , -d W0221 , -d E1102, -d E0611 ]
