name: Update Documentation

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.type }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    # paths:
    #     - 'docs/**'

jobs:
  updatedocumentation:
    runs-on: ubuntu-latest
    name: "Update Documentation"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy Documentation
        uses: ./.github/actions/build-documentation
        env:
            DOCS_SRC: ./docs
            DEST: ./out
      - name: GitHub Pages Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
            BUILD_DIR: ./docs
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BASE_BRANCH: master # The branch the action should deploy from.
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: docs # The folder the action should deploy.
