name: Deploy

on:
  push:
    branches:
      - master

jobs:
  updatedocumentation:
    runs-on: ubuntu-latest
    name: "Update Documentation"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Documentation
        uses: ./.github/actions/build-documentation
        env:
            DOCS_SRC: ./docs
            DEST: ./out
      - name: GitHub Pages Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
            BUILD_DIR: ./docs
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BASE_BRANCH: master # The branch the action should deploy from.
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: docs # The folder the action should deploy.
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to PyPI"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Autoadd release Tags
        uses: jaliborc/action-general-autotag@7d2ae9f
        id:   autotag
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source_file: "src/miniflask/__init__.py"
          # extraction_regex: "^__version__\\s*=\\s*\"(\\d[\\d\\.]+)\""
          extraction_regex: "__version__\\s*=\\s*\"(\\d[\\d\\.]+)\""
          tag_message: "Release"
          tag_format: "v{version}"
      - name: Set up Python
        if: steps.autotag.outputs.tagname
        uses: actions/setup-python@v1
        with:
            python-version: '3.x'
      - name: Install dependencies
        if: steps.autotag.outputs.tagname
        run: python setup.py sdist
      - name: Publish a Python distribution to PyPI
        if: steps.autotag.outputs.tagname
        uses: pypa/gh-action-pypi-publish@master
        with:
            user: __token__
            password: ${{ secrets.pypi_password }}

# Guide: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions
