name: Testing

on: [push]

jobs:
  Pytest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install flake8 pylint pytest
        # install deps for pylint
        python -m pip install colored
    - name: Syntax Check of Tests
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 tests --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Static Analysis of Tests (Modules)
      run: |
        flake8 tests --count --ignore E501 --statistics
        PYTHONPATH=$(pwd)/src find tests -type d -exec test -e '{}'/.module \; -exec pylint -d W0511 -d C0114 -d C0116 -d C0115 -d C0301 -d C0103 -d R0913 -d R0914 -d R0902 -d R0912 -d R0801 -d W0212 -d W0223 -d E1101 -d W0221 -d E1102 '{}' +
        PYTHONPATH=$(pwd)/src find tests -type d -exec test -e '{}'/.module \; -exec pylint --exit-zero '{}' +
    - name: Pytest
      run: pytest
